server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: false

springdoc:
  swagger-ui:
    enabled:true
spring:
  application:
    name: homehub-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/homehub
    username: postgres
    password: 23z7bnn3
  jpa:
    hibernate:
      ddl-auto: update  # or validate/create depending on your needs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: 123
      password: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: guptaayush1280@gmail.com
    password: lvbpparbietpkpjp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0


app:
  name: HomeHub
  url: http://localhost:8081

jwt:
  secret: G9X3G7v9SChJbiEZ1eyMbXBnT4XBCV3ztctGb8AXU8c=

